package main

import (
	"bytes"
	"fmt"
	"github.com/gorilla/mux"
	"io"
	"io/ioutil"
	"log"
	"net/http"
	"time"
)

type PCKCert struct {
	platformManifest string `json:"platformManifest"`
	pceid            string `json:"pceid"`
}

type PcsOutput struct {
	Pckcert []byte
	Pckcrl  []byte
	Qeid    []byte
	Tcb     []byte
	err     error
}

var dummy PcsOutput

func GetPCKCertificateCB(w http.ResponseWriter, r *http.Request) {
	time.Sleep(5 * time.Millisecond)
	var log bytes.Buffer
	rsp := io.MultiWriter(w, &log)
	w.Header().Write(&log)
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Sgx-Fmspc", "123456789012")
	w.Header().Set("Sgx-Pck-Certificate-Ca-Type", "processor")
	w.Header().Set("Request-Id", "02e862b082b94270ba9d10d05283d5d3")
	w.Header().Set("SGX-PCK-Certificate-Issuer-Chain", "-----BEGIN%20CERTIFICATE-----%0AMIIClzCCAj6gAwIBAgIVANDoqtp11%2FkuSReYPHsUZdDV8llNMAoGCCqGSM49BAMC%0AMGgxGjAYBgNVBAMMEUludGVsIFNHWCBSb290IENBMRowGAYDVQQKDBFJbnRlbCBD%0Ab3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQsw%0ACQYDVQQGEwJVUzAeFw0xODA1MjExMDQ1MDhaFw0zMzA1MjExMDQ1MDhaMHExIzAh%0ABgNVBAMMGkludGVsIFNHWCBQQ0sgUHJvY2Vzc29yIENBMRowGAYDVQQKDBFJbnRl%0AbCBDb3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNB%0AMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL9q%2BNMp2IOg%0Atdl1bk%2FuWZ5%2BTGQm8aCi8z78fs%2BfKCQ3d%2BuDzXnVTAT2ZhDCifyIuJwvN3wNBp9i%0AHBSSMJMJrBOjgbswgbgwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqww%0AUgYDVR0fBEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNl%0AcnZpY2VzLmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5jcmwwHQYDVR0OBBYEFNDo%0Aqtp11%2FkuSReYPHsUZdDV8llNMA4GA1UdDwEB%2FwQEAwIBBjASBgNVHRMBAf8ECDAG%0AAQH%2FAgEAMAoGCCqGSM49BAMCA0cAMEQCIC%2F9j%2B84T%2BHztVO%2FsOQBWJbSd%2B%2F2uexK%0A4%2BaA0jcFBLcpAiA3dhMrF5cD52t6FqMvAIpj8XdGmy2beeljLJK%2BpzpcRA%3D%3D%0A-----END%20CERTIFICATE-----%0A-----BEGIN%20CERTIFICATE-----%0AMIICjjCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw%0AaDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv%0AcnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ%0ABgNVBAYTAlVTMB4XDTE4MDUyMTEwNDExMVoXDTMzMDUyMTEwNDExMFowaDEaMBgG%0AA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0%0AaW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT%0AAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj%2FiPWsCzaEKi7%0A1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB%0AuzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ%0AMEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50%0AZWwuY29tL0ludGVsU0dYUm9vdENBLmNybDAdBgNVHQ4EFgQUImUM1lqdNInzg7SV%0AUr9QGzknBqwwDgYDVR0PAQH%2FBAQDAgEGMBIGA1UdEwEB%2FwQIMAYBAf8CAQEwCgYI%0AKoZIzj0EAwIDSAAwRQIgQQs%2F08rycdPauCFk8UPQXCMAlsloBe7NwaQGTcdpa0EC%0AIQCUt8SGvxKmjpcM%2Fz0WP9Dvo8h2k5du1iWDdBkAn%2B0iiA%3D%3D%0A-----END%20CERTIFICATE-----")
	w.WriteHeader(http.StatusOK) // HTTP 200
	rsp.Write([]byte(dummy.Pckcert))
}

func GetPCKCRLCB(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/x-pem-file")
	w.Header().Set("Request-Id", "02e862b082b94270ba9d10d05283d5d3")
	w.Header().Set("Sgx-Pck-Crl-Issuer-Chain", "-----BEGIN%20CERTIFICATE-----%0AMIIClzCCAj6gAwIBAgIVANDoqtp11%2FkuSReYPHsUZdDV8llNMAoGCCqGSM49BAMC%0AMGgxGjAYBgNVBAMMEUludGVsIFNHWCBSb290IENBMRowGAYDVQQKDBFJbnRlbCBD%0Ab3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQsw%0ACQYDVQQGEwJVUzAeFw0xODA1MjExMDQ1MDhaFw0zMzA1MjExMDQ1MDhaMHExIzAh%0ABgNVBAMMGkludGVsIFNHWCBQQ0sgUHJvY2Vzc29yIENBMRowGAYDVQQKDBFJbnRl%0AbCBDb3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNB%0AMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL9q%2BNMp2IOg%0Atdl1bk%2FuWZ5%2BTGQm8aCi8z78fs%2BfKCQ3d%2BuDzXnVTAT2ZhDCifyIuJwvN3wNBp9i%0AHBSSMJMJrBOjgbswgbgwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqww%0AUgYDVR0fBEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNl%0AcnZpY2VzLmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5jcmwwHQYDVR0OBBYEFNDo%0Aqtp11%2FkuSReYPHsUZdDV8llNMA4GA1UdDwEB%2FwQEAwIBBjASBgNVHRMBAf8ECDAG%0AAQH%2FAgEAMAoGCCqGSM49BAMCA0cAMEQCIC%2F9j%2B84T%2BHztVO%2FsOQBWJbSd%2B%2F2uexK%0A4%2BaA0jcFBLcpAiA3dhMrF5cD52t6FqMvAIpj8XdGmy2beeljLJK%2BpzpcRA%3D%3D%0A-----END%20CERTIFICATE-----%0A-----BEGIN%20CERTIFICATE-----%0AMIICjjCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw%0AaDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv%0AcnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ%0ABgNVBAYTAlVTMB4XDTE4MDUyMTEwNDExMVoXDTMzMDUyMTEwNDExMFowaDEaMBgG%0AA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0%0AaW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT%0AAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj%2FiPWsCzaEKi7%0A1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB%0AuzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ%0AMEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50%0AZWwuY29tL0ludGVsU0dYUm9vdENBLmNybDAdBgNVHQ4EFgQUImUM1lqdNInzg7SV%0AUr9QGzknBqwwDgYDVR0PAQH%2FBAQDAgEGMBIGA1UdEwEB%2FwQIMAYBAf8CAQEwCgYI%0AKoZIzj0EAwIDSAAwRQIgQQs%2F08rycdPauCFk8UPQXCMAlsloBe7NwaQGTcdpa0EC%0AIQCUt8SGvxKmjpcM%2Fz0WP9Dvo8h2k5du1iWDdBkAn%2B0iiA%3D%3D%0A-----END%20CERTIFICATE-----%0A")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(dummy.Pckcrl))
}

func GetTCBInfoCB(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Request-Id", "02e862b082b94270ba9d10d05283d5d3")
	w.Header().Set("Sgx-Tcb-Info-Issuer-Chain", "-----BEGIN%20CERTIFICATE-----%0AMIIClzCCAj6gAwIBAgIVANDoqtp11%2FkuSReYPHsUZdDV8llNMAoGCCqGSM49BAMC%0AMGgxGjAYBgNVBAMMEUludGVsIFNHWCBSb290IENBMRowGAYDVQQKDBFJbnRlbCBD%0Ab3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQsw%0ACQYDVQQGEwJVUzAeFw0xODA1MjExMDQ1MDhaFw0zMzA1MjExMDQ1MDhaMHExIzAh%0ABgNVBAMMGkludGVsIFNHWCBQQ0sgUHJvY2Vzc29yIENBMRowGAYDVQQKDBFJbnRl%0AbCBDb3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNB%0AMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL9q%2BNMp2IOg%0Atdl1bk%2FuWZ5%2BTGQm8aCi8z78fs%2BfKCQ3d%2BuDzXnVTAT2ZhDCifyIuJwvN3wNBp9i%0AHBSSMJMJrBOjgbswgbgwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqww%0AUgYDVR0fBEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNl%0AcnZpY2VzLmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5jcmwwHQYDVR0OBBYEFNDo%0Aqtp11%2FkuSReYPHsUZdDV8llNMA4GA1UdDwEB%2FwQEAwIBBjASBgNVHRMBAf8ECDAG%0AAQH%2FAgEAMAoGCCqGSM49BAMCA0cAMEQCIC%2F9j%2B84T%2BHztVO%2FsOQBWJbSd%2B%2F2uexK%0A4%2BaA0jcFBLcpAiA3dhMrF5cD52t6FqMvAIpj8XdGmy2beeljLJK%2BpzpcRA%3D%3D%0A-----END%20CERTIFICATE-----%0A-----BEGIN%20CERTIFICATE-----%0AMIICjjCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw%0AaDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv%0AcnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ%0ABgNVBAYTAlVTMB4XDTE4MDUyMTEwNDExMVoXDTMzMDUyMTEwNDExMFowaDEaMBgG%0AA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0%0AaW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT%0AAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj%2FiPWsCzaEKi7%0A1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB%0AuzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ%0AMEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50%0AZWwuY29tL0ludGVsU0dYUm9vdENBLmNybDAdBgNVHQ4EFgQUImUM1lqdNInzg7SV%0AUr9QGzknBqwwDgYDVR0PAQH%2FBAQDAgEGMBIGA1UdEwEB%2FwQIMAYBAf8CAQEwCgYI%0AKoZIzj0EAwIDSAAwRQIgQQs%2F08rycdPauCFk8UPQXCMAlsloBe7NwaQGTcdpa0EC%0AIQCUt8SGvxKmjpcM%2Fz0WP9Dvo8h2k5du1iWDdBkAn%2B0iiA%3D%3D%0A-----END%20CERTIFICATE-----%0A")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(dummy.Tcb))
}

func GetQEIdentityInfoCB(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Request-Id", "02e862b082b94270ba9d10d05283d5d3")
	w.Header().Set("Sgx-Enclave-Identity-Issuer-Chain", "-----BEGIN%20CERTIFICATE-----%0AMIIClzCCAj6gAwIBAgIVANDoqtp11%2FkuSReYPHsUZdDV8llNMAoGCCqGSM49BAMC%0AMGgxGjAYBgNVBAMMEUludGVsIFNHWCBSb290IENBMRowGAYDVQQKDBFJbnRlbCBD%0Ab3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQsw%0ACQYDVQQGEwJVUzAeFw0xODA1MjExMDQ1MDhaFw0zMzA1MjExMDQ1MDhaMHExIzAh%0ABgNVBAMMGkludGVsIFNHWCBQQ0sgUHJvY2Vzc29yIENBMRowGAYDVQQKDBFJbnRl%0AbCBDb3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNB%0AMQswCQYDVQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABL9q%2BNMp2IOg%0Atdl1bk%2FuWZ5%2BTGQm8aCi8z78fs%2BfKCQ3d%2BuDzXnVTAT2ZhDCifyIuJwvN3wNBp9i%0AHBSSMJMJrBOjgbswgbgwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqww%0AUgYDVR0fBEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNl%0AcnZpY2VzLmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5jcmwwHQYDVR0OBBYEFNDo%0Aqtp11%2FkuSReYPHsUZdDV8llNMA4GA1UdDwEB%2FwQEAwIBBjASBgNVHRMBAf8ECDAG%0AAQH%2FAgEAMAoGCCqGSM49BAMCA0cAMEQCIC%2F9j%2B84T%2BHztVO%2FsOQBWJbSd%2B%2F2uexK%0A4%2BaA0jcFBLcpAiA3dhMrF5cD52t6FqMvAIpj8XdGmy2beeljLJK%2BpzpcRA%3D%3D%0A-----END%20CERTIFICATE-----%0A-----BEGIN%20CERTIFICATE-----%0AMIICjjCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw%0AaDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv%0AcnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ%0ABgNVBAYTAlVTMB4XDTE4MDUyMTEwNDExMVoXDTMzMDUyMTEwNDExMFowaDEaMBgG%0AA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0%0AaW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT%0AAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj%2FiPWsCzaEKi7%0A1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB%0AuzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ%0AMEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50%0AZWwuY29tL0ludGVsU0dYUm9vdENBLmNybDAdBgNVHQ4EFgQUImUM1lqdNInzg7SV%0AUr9QGzknBqwwDgYDVR0PAQH%2FBAQDAgEGMBIGA1UdEwEB%2FwQIMAYBAf8CAQEwCgYI%0AKoZIzj0EAwIDSAAwRQIgQQs%2F08rycdPauCFk8UPQXCMAlsloBe7NwaQGTcdpa0EC%0AIQCUt8SGvxKmjpcM%2Fz0WP9Dvo8h2k5du1iWDdBkAn%2B0iiA%3D%3D%0A-----END%20CERTIFICATE-----%0A")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(dummy.Qeid))
}

func main() {
	dummy.Pckcert, dummy.err = ioutil.ReadFile("pckcert.txt")
	dummy.Pckcrl, dummy.err = ioutil.ReadFile("pckcrl.txt")
	dummy.Qeid, dummy.err = ioutil.ReadFile("qeid.txt")
	dummy.Tcb, dummy.err = ioutil.ReadFile("tcb.txt")
	// Create Router, set routes
	r := mux.NewRouter()
	r.HandleFunc("/sgx/certification/v3/pckcerts", GetPCKCertificateCB).Methods("POST")
	r.HandleFunc("/sgx/certification/v3/pckcrl", GetPCKCRLCB).Methods("GET")
	r.HandleFunc("/sgx/certification/v3/tcb", GetTCBInfoCB).Methods("GET")
	r.HandleFunc("/sgx/certification/v3/qe/identity", GetQEIdentityInfoCB).Methods("GET")
	fmt.Println("Request fullfilling")
	log.Fatal(http.ListenAndServe(":8080", r))
}
